version: '3.9'

services:
  web:
    image: my-django-app:latest
    build: .
    command: python /app/InionBlog/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - db_volume:/app/InionBlog/db.sqlite3

volumes:
  static_volume:
  media_volume:
  db_volume:
